Fix #13: Add golang to the database
CSwala/awesome-computer-science pull request #121
Opened 2021-03-15 09:02 UTC by jonathanalvares9009

## Explanation

This PR adds information regarding Golang Programming Language.
It fixes #13 
## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR does not break any part of the existing code.
- [x] The PR creator have carefully read & adher to the contributing guidelines of the project.
- [x] The PR is made to the branch that's **called** "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "main" and not on any other branch.
- [x] Have you followed the guidelines in the Contributing document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/CSwala/awesome-computer-science/pulls) for the same tech?
- [x] Is your submission is according to the desired pattern ?
- [x] Have you placed the contents in the `Readme.md` keeping the sorting order in mind ?

Does you submission include -

- [x]	Category/Type
- [x]	Official Documnetation  
- [x]	Best YouTube creators  
- [x]	Useful Websites  
- [x]	Dedicated Github page 
- [x]	Best Courses  
- [x]	Ohter Tips / Hacks

2021-03-15 09:04 UTC, riturajjain2000 requested changes
Find more useful websites and other content like GH pages as GOlang has a lot of content

2021-03-15 10:14 UTC, jonathanalvares9009 commented
@riturajjain2000 added more info

2021-03-15 15:25 UTC, riturajjain2000 commented on Dictionary.json
> +		"Dedicated GH page7": "https://github.com/golang/appengine",
https://github.com/avelino/awesome-go
add awesme pages also
search for awesome golang on GH and add them,

2021-03-15 15:25 UTC, riturajjain2000 requested changes
Add awesome pages , as they are the best in class from the community

2021-03-16 10:07 UTC, riturajjain2000 approved these changes

2021-03-16 10:07 UTC, merged