Add Reason
CSwala/awesome-computer-science pull request #258
Opened 2021-04-12 16:22 UTC by viralkumar28

## Explanation
- Added Reason in database.

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR does not break any part of the existing code.
- [x] The PR creator have carefully read & adher to the contributing guidelines of the project.
- [x] The PR is made to the branch that's **called** "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] Have you followed the guidelines in the Contributing document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/CSwala/awesome-computer-science/pulls) for the same tech?
- [x] Is your submission is according to the desired pattern ?
- [x] Have you placed the contents in the `Readme.md` keeping the sorting order in mind ?
- [x] Have you placed the contents in the `Dictionary.json` keeping the sorting order in mind ?

Does you submission include -

- [ ]	Category/Type
- [ ]	Official Documnetation  
- [ ]	Best YouTube creators  
- [ ]	Useful Websites  
- [ ]	Dedicated Github page 
- [ ]	Best Courses  
- [ ]	Ohter Tips / Hacks

2021-04-12 17:35 UTC, ddvader44 approved these changes

2021-04-13 06:14 UTC, riturajjain2000 commented on README.md
> +=======
Why is this line here ?

2021-04-13 06:15 UTC, riturajjain2000 requested changes
Reason will come after React Native

2021-04-13 08:07 UTC, viralkumar28 commented on README.md
> +=======
By mistake i wrote that.

2021-04-14 10:23 UTC, riturajjain2000 approved these changes

2021-04-14 10:23 UTC, merged